package com.example.genbrush.ui.localization

data class AppStrings(
    // Bottom navigation
    val navGenerate: String,
    val navEdit: String,
    val navGallery: String,
    val navSettings: String,

    // Text-to-Image screen
    val txt2imgTitle: String,
    val txt2imgPromptLabel: String,
    val txt2imgPromptPlaceholder: String,
    val txt2imgNegLabel: String,
    val txt2imgNegPlaceholder: String,
    val txt2imgModel: String,
    val txt2imgSize: String,
    val txt2imgButton: String,

    // Image Edit screen
    val editTitle: String,
    val editTapToSelect: String,
    val editFromLibrary: String,
    val editSourceDesc: String,
    val editChange: String,
    val editPromptLabel: String,
    val editPromptPlaceholder: String,
    val editModel: String,
    val editButton: String,

    // Gallery screen
    val galleryTitle: String,
    val galleryEmpty: String,
    val galleryEmptyHint: String,
    val galleryImageNotFound: String,
    val gallerySave: String,
    val galleryShare: String,
    val galleryDelete: String,
    val galleryCopyPrompt: String,
    val galleryPromptCopied: String,
    val galleryShareTitle: String,
    val galleryFavorite: String,
    val galleryUnfavorite: String,
    val galleryShowFavorites: String,
    val gallerySearchHint: String,
    val galleryFilterAll: String,
    val galleryFilterTxt2img: String,
    val galleryFilterEdit: String,
    val gallerySortNewest: String,
    val gallerySortOldest: String,
    val gallerySortFavFirst: String,

    // Delete confirmation
    val deleteConfirmTitle: String,
    val deleteConfirmMessage: String,

    // Common
    val commonConfirm: String,
    val commonCancel: String,
    val commonSaved: String,

    // Full image viewer
    val viewerTitle: String,
    val viewerBack: String,
    val viewerSave: String,
    val viewerShare: String,
    val viewerDelete: String,
    val viewerShareTitle: String,
    val viewerDesc: String,
    val viewerNotFound: String,

    // Image result card
    val resultDesc: String,
    val resultTxt2img: String,
    val resultEdit: String,
    val resultSave: String,
    val resultShare: String,
    val resultShareTitle: String,
    val resultSavedBy: String,

    // Loading overlay
    val loadingMsg: String,
    val loadingHint: String,
    val loadingHintSd: String,

    // Settings screen
    val settingsTitle: String,
    val settingsSaved: String,
    val settingsApiConfig: String,
    val settingsApiKeyLabel: String,
    val settingsApiPlaceholder: String,
    val settingsHide: String,
    val settingsShow: String,
    val settingsApiKeyHint: String,
    val settingsDefaults: String,
    val settingsDefaultModel: String,
    val settingsDefaultSize: String,
    val settingsSave: String,
    val settingsAbout: String,
    val settingsAboutDesc: String,
    val settingsModels: String,
    val settingsVersion: String,
    val settingsLanguage: String,

    // Model management
    val settingsModelManagement: String,
    val settingsPresetModels: String,
    val settingsGenerationModels: String,
    val settingsEditModels: String,
    val settingsCustomModels: String,
    val settingsAddCustomModel: String,
    val settingsCustomModelHint: String,
    val settingsAddButton: String,
    val settingsRemoveModel: String,
    val settingsModelExists: String,
    val settingsModelEmpty: String,

    // Section titles
    val sectionBackendServer: String,
    val sectionGenModels: String,
    val sectionEditModels: String,

    // Tab labels
    val tabDashScope: String,
    val tabSdWebUI: String,

    // SD WebUI settings
    val settingsBackend: String,
    val settingsBackendDashScope: String,
    val settingsBackendSdWebUI: String,
    val settingsManageModels: String,
    val settingsSdServerConfig: String,
    val settingsSdServerUrl: String,
    val settingsSdServerHint: String,
    val settingsSdTestConnection: String,
    val settingsSdConnected: String,

    // Common
    val modelLabel: String,
    val sizeLabel: String,

    // LoRA
    val loraTitle: String,
    val loraNone: String,
    val loraSelected: String,
    val loraWeight: String,

    // Data Migration
    val migrationTitle: String,
    val migrationExport: String,
    val migrationImport: String,
    val migrationExportSuccess: String,
    val migrationImportSuccess: String,
    val migrationError: String,
    val migrationExporting: String,
    val migrationImporting: String,

    // Error messages
    val errApiKey: String,
    val errInvalidKey: String,
    val errRateLimit: String,
    val errContentSafety: String,
    val errNetwork: String,
    val errServer: String,
    val errUnknown: String,
    val errEnterPrompt: String,
    val errSelectImage: String,
    val errEnterEditPrompt: String,
    val errSetApiKey: String,
    val errEmptyResponse: String,
    val errUnknownApi: String,
    val errNoImageGenerated: String,
    val errNoImageUrl: String,
    val errSaveFailed: String,
    val errEditSaveFailed: String,
    val errCannotOpen: String,
    val errDecodeFailed: String
) {
    companion object {
        val ZH = AppStrings(
            navGenerate = "生成",
            navEdit = "编辑",
            navGallery = "相册",
            navSettings = "设置",
            txt2imgTitle = "文生图",
            txt2imgPromptLabel = "提示词",
            txt2imgPromptPlaceholder = "描述你想生成的图片...",
            txt2imgNegLabel = "反向提示词（可选）",
            txt2imgNegPlaceholder = "不想出现的内容...",
            txt2imgModel = "模型",
            txt2imgSize = "尺寸",
            txt2imgButton = "生成图片",
            editTitle = "图像编辑",
            editTapToSelect = "点击选择图片",
            editFromLibrary = "从相册中选择",
            editSourceDesc = "原图",
            editChange = "更换",
            editPromptLabel = "编辑提示词",
            editPromptPlaceholder = "描述你想如何编辑图片...",
            editModel = "模型",
            editButton = "编辑图片",
            galleryTitle = "相册",
            galleryEmpty = "暂无图片",
            galleryEmptyHint = "生成你的第一张图片吧！",
            galleryImageNotFound = "图片未找到",
            gallerySave = "保存到相册",
            galleryShare = "分享",
            galleryDelete = "删除",
            galleryCopyPrompt = "复制提示词",
            galleryPromptCopied = "提示词已复制",
            galleryShareTitle = "分享图片",
            galleryFavorite = "收藏",
            galleryUnfavorite = "取消收藏",
            galleryShowFavorites = "收藏筛选",
            gallerySearchHint = "搜索提示词...",
            galleryFilterAll = "全部",
            galleryFilterTxt2img = "文生图",
            galleryFilterEdit = "编辑",
            gallerySortNewest = "最新",
            gallerySortOldest = "最早",
            gallerySortFavFirst = "收藏优先",
            deleteConfirmTitle = "确认删除",
            deleteConfirmMessage = "确定删除这张图片吗？此操作不可恢复。",
            commonConfirm = "确认",
            commonCancel = "取消",
            commonSaved = "已保存",
            viewerTitle = "图片详情",
            viewerBack = "返回",
            viewerSave = "保存",
            viewerShare = "分享",
            viewerDelete = "删除",
            viewerShareTitle = "分享图片",
            viewerDesc = "原图查看",
            viewerNotFound = "图片未找到",
            resultDesc = "生成的图片",
            resultTxt2img = "文生图",
            resultEdit = "图像编辑",
            resultSave = "保存",
            resultShare = "分享",
            resultShareTitle = "分享图片",
            resultSavedBy = "由 GenBrush 生成",
            loadingMsg = "正在生成图片...",
            loadingHint = "预计需要 10-30 秒",
            loadingHintSd = "本地 SD 生成较慢，预计需要 1-3 分钟",
            settingsTitle = "设置",
            settingsSaved = "设置已保存",
            settingsApiConfig = "API 配置",
            settingsApiKeyLabel = "DashScope API Key",
            settingsApiPlaceholder = "sk-...",
            settingsHide = "隐藏",
            settingsShow = "显示",
            settingsApiKeyHint = "请输入阿里云百炼平台的 DashScope API Key。",
            settingsDefaults = "默认设置",
            settingsDefaultModel = "默认模型",
            settingsDefaultSize = "默认尺寸",
            settingsSave = "保存设置",
            settingsAbout = "关于",
            settingsAboutDesc = "AI 图像生成与编辑工具",
            settingsModels = "模型：qwen-image-2.0-pro-2026-04-22 / qwen-image-2.0-pro / qwen-image-2.0",
            settingsVersion = "版本",
            settingsLanguage = "语言",
            tabDashScope = "DashScope",
            tabSdWebUI = "SD WebUI",
            settingsBackend = "后端服务",
            settingsBackendDashScope = "DashScope (阿里云百炼)",
            settingsBackendSdWebUI = "SD WebUI Forge (本地)",
            settingsManageModels = "管理生成模型与编辑模型",
            settingsSdServerConfig = "SD 服务器配置",
            settingsSdServerUrl = "服务器地址",
            settingsSdServerHint = "手机和电脑需在同一局域网，格式：http://IP:端口",
            settingsSdTestConnection = "测试连接",
            settingsSdConnected = "连接成功",
            settingsModelManagement = "模型管理",
            settingsPresetModels = "预置模型",
            settingsGenerationModels = "生成模型",
            settingsEditModels = "编辑模型",
            settingsCustomModels = "自定义模型",
            settingsAddCustomModel = "添加自定义模型",
            settingsCustomModelHint = "输入模型名称",
            settingsAddButton = "添加",
            settingsRemoveModel = "删除",
            settingsModelExists = "模型已存在",
            settingsModelEmpty = "模型名称不能为空",
            sectionBackendServer = "后端与服务器",
            sectionGenModels = "生成模型",
            sectionEditModels = "编辑模型",
            modelLabel = "模型",
            sizeLabel = "尺寸",
            loraTitle = "LoRA 模型",
            loraNone = "无可用 LoRA",
            loraSelected = "已选 %d 个",
            loraWeight = "权重",
            migrationTitle = "数据迁移",
            migrationExport = "导出数据",
            migrationImport = "导入数据",
            migrationExportSuccess = "导出成功，共 %d 张图片",
            migrationImportSuccess = "导入成功，新增 %d 张图片",
            migrationError = "操作失败：",
            migrationExporting = "正在导出...",
            migrationImporting = "正在导入...",
            errApiKey = "请先在设置中配置 API Key",
            errInvalidKey = "API Key 无效，请在设置中检查。",
            errRateLimit = "请求频率过高，请稍后再试。",
            errContentSafety = "内容安全审核未通过，请更换提示词重试。",
            errNetwork = "网络错误，请检查网络连接。",
            errServer = "服务器错误，请稍后重试。",
            errUnknown = "未知错误",
            errEnterPrompt = "请输入提示词",
            errSelectImage = "请选择一张图片",
            errEnterEditPrompt = "请输入编辑提示词",
            errSetApiKey = "请先在设置中配置 API Key",
            errEmptyResponse = "响应内容为空",
            errUnknownApi = "未知 API 错误",
            errNoImageGenerated = "未生成图片，提示词可能被内容安全过滤器拦截。",
            errNoImageUrl = "响应中未包含图片",
            errSaveFailed = "保存图片失败：",
            errEditSaveFailed = "保存编辑后的图片失败：",
            errCannotOpen = "无法打开图片",
            errDecodeFailed = "解码图片失败"
        )

        val EN = AppStrings(
            navGenerate = "Generate",
            navEdit = "Edit",
            navGallery = "Gallery",
            navSettings = "Settings",
            txt2imgTitle = "Text to Image",
            txt2imgPromptLabel = "Prompt",
            txt2imgPromptPlaceholder = "Describe the image you want to generate...",
            txt2imgNegLabel = "Negative Prompt (optional)",
            txt2imgNegPlaceholder = "What to avoid...",
            txt2imgModel = "Model",
            txt2imgSize = "Size",
            txt2imgButton = "Generate Image",
            editTitle = "Image Edit",
            editTapToSelect = "Tap to select an image",
            editFromLibrary = "Choose from your photo library",
            editSourceDesc = "Source image",
            editChange = "Change",
            editPromptLabel = "Editing Prompt",
            editPromptPlaceholder = "Describe how to edit the image...",
            editModel = "Model",
            editButton = "Edit Image",
            galleryTitle = "Gallery",
            galleryEmpty = "No images yet",
            galleryEmptyHint = "Generate your first image!",
            galleryImageNotFound = "Image not found",
            gallerySave = "Save to Gallery",
            galleryShare = "Share",
            galleryDelete = "Delete",
            galleryCopyPrompt = "Copy Prompt",
            galleryPromptCopied = "Prompt copied",
            galleryShareTitle = "Share Image",
            galleryFavorite = "Favorite",
            galleryUnfavorite = "Unfavorite",
            galleryShowFavorites = "Show Favorites",
            gallerySearchHint = "Search prompts...",
            galleryFilterAll = "All",
            galleryFilterTxt2img = "Text to Image",
            galleryFilterEdit = "Edit",
            gallerySortNewest = "Newest",
            gallerySortOldest = "Oldest",
            gallerySortFavFirst = "Favorites First",
            deleteConfirmTitle = "Confirm Delete",
            deleteConfirmMessage = "Are you sure you want to delete this image? This cannot be undone.",
            commonConfirm = "Confirm",
            commonCancel = "Cancel",
            commonSaved = "Saved",
            viewerTitle = "Image",
            viewerBack = "Back",
            viewerSave = "Save",
            viewerShare = "Share",
            viewerDelete = "Delete",
            viewerShareTitle = "Share Image",
            viewerDesc = "Full size image",
            viewerNotFound = "Image not found",
            resultDesc = "Generated image",
            resultTxt2img = "Text to Image",
            resultEdit = "Image Edit",
            resultSave = "Save",
            resultShare = "Share",
            resultShareTitle = "Share Image",
            resultSavedBy = "Generated by GenBrush",
            loadingMsg = "Generating image...",
            loadingHint = "This may take 10-30 seconds",
            loadingHintSd = "Local SD generation is slower, may take 1-3 minutes",
            settingsTitle = "Settings",
            settingsSaved = "Settings saved",
            settingsApiConfig = "API Configuration",
            settingsApiKeyLabel = "DashScope API Key",
            settingsApiPlaceholder = "sk-...",
            settingsHide = "Hide",
            settingsShow = "Show",
            settingsApiKeyHint = "Enter your DashScope API key from Alibaba Cloud console.",
            settingsDefaults = "Defaults",
            settingsDefaultModel = "Default Model",
            settingsDefaultSize = "Default Size",
            settingsSave = "Save Settings",
            settingsAbout = "About",
            settingsAboutDesc = "AI Image Generation & Editing Tool",
            settingsModels = "Model: qwen-image-2.0-pro-2026-04-22 / qwen-image-2.0-pro / qwen-image-2.0",
            settingsVersion = "Version",
            settingsLanguage = "Language",
            tabDashScope = "DashScope",
            tabSdWebUI = "SD WebUI",
            settingsBackend = "Backend",
            settingsBackendDashScope = "DashScope (Alibaba Cloud)",
            settingsBackendSdWebUI = "SD WebUI Forge (Local)",
            settingsManageModels = "Manage generation and editing models",
            settingsSdServerConfig = "SD Server Configuration",
            settingsSdServerUrl = "Server URL",
            settingsSdServerHint = "Phone and PC must be on the same LAN. Format: http://IP:port",
            settingsSdTestConnection = "Test Connection",
            settingsSdConnected = "Connected",
            settingsModelManagement = "Model Management",
            settingsPresetModels = "Preset Models",
            settingsGenerationModels = "Generation Models",
            settingsEditModels = "Edit Models",
            settingsCustomModels = "Custom Models",
            settingsAddCustomModel = "Add Custom Model",
            settingsCustomModelHint = "Enter model name",
            settingsAddButton = "Add",
            settingsRemoveModel = "Remove",
            settingsModelExists = "Model already exists",
            settingsModelEmpty = "Model name cannot be empty",
            sectionBackendServer = "Backend & Server",
            sectionGenModels = "Generation Models",
            sectionEditModels = "Edit Models",
            modelLabel = "Model",
            sizeLabel = "Size",
            loraTitle = "LoRA Models",
            loraNone = "No LoRA available",
            loraSelected = "%d selected",
            loraWeight = "Weight",
            migrationTitle = "Data Migration",
            migrationExport = "Export Data",
            migrationImport = "Import Data",
            migrationExportSuccess = "Exported successfully, %d images",
            migrationImportSuccess = "Imported successfully, %d new images",
            migrationError = "Operation failed: ",
            migrationExporting = "Exporting...",
            migrationImporting = "Importing...",
            errApiKey = "Please set your API key in Settings",
            errInvalidKey = "Invalid API key. Please check Settings.",
            errRateLimit = "Rate limited. Please wait and try again.",
            errContentSafety = "Content safety check failed. Please try a different prompt.",
            errNetwork = "Network error. Please check your internet connection.",
            errServer = "Server error. Please try again later.",
            errUnknown = "Unknown error",
            errEnterPrompt = "Please enter a prompt",
            errSelectImage = "Please select an image",
            errEnterEditPrompt = "Please enter an editing prompt",
            errSetApiKey = "Please set your API key in Settings",
            errEmptyResponse = "Empty response body",
            errUnknownApi = "Unknown API error",
            errNoImageGenerated = "No images generated. The prompt may have been blocked by content safety filters.",
            errNoImageUrl = "No image URL in response",
            errSaveFailed = "Failed to save generated image: ",
            errEditSaveFailed = "Failed to save edited image: ",
            errCannotOpen = "Cannot open image",
            errDecodeFailed = "Failed to decode image"
        )
    }
}
