package com.example.qwen_image.ui.localization

data class AppStrings(
    // Bottom navigation
    val navGenerate: String,
    val navEdit: String,
    val navGallery: String,
    val navSettings: String,

    // Text-to-Image screen
    val txt2imgTitle: String,
    val txt2imgPromptLabel: String,
    val txt2imgPromptPlaceholder: String,
    val txt2imgNegLabel: String,
    val txt2imgNegPlaceholder: String,
    val txt2imgModel: String,
    val txt2imgSize: String,
    val txt2imgButton: String,

    // Image Edit screen
    val editTitle: String,
    val editTapToSelect: String,
    val editFromLibrary: String,
    val editSourceDesc: String,
    val editChange: String,
    val editPromptLabel: String,
    val editPromptPlaceholder: String,
    val editModel: String,
    val editButton: String,

    // Gallery screen
    val galleryTitle: String,
    val galleryEmpty: String,
    val galleryEmptyHint: String,
    val galleryImageNotFound: String,
    val gallerySave: String,
    val galleryShare: String,
    val galleryDelete: String,
    val galleryCopyPrompt: String,
    val galleryPromptCopied: String,
    val galleryShareTitle: String,

    // Full image viewer
    val viewerTitle: String,
    val viewerBack: String,
    val viewerSave: String,
    val viewerShare: String,
    val viewerDelete: String,
    val viewerShareTitle: String,
    val viewerDesc: String,
    val viewerNotFound: String,

    // Image result card
    val resultDesc: String,
    val resultTxt2img: String,
    val resultEdit: String,
    val resultSave: String,
    val resultShare: String,
    val resultShareTitle: String,
    val resultSavedBy: String,

    // Loading overlay
    val loadingMsg: String,
    val loadingHint: String,

    // Settings screen
    val settingsTitle: String,
    val settingsSaved: String,
    val settingsApiConfig: String,
    val settingsApiKeyLabel: String,
    val settingsApiPlaceholder: String,
    val settingsHide: String,
    val settingsShow: String,
    val settingsApiKeyHint: String,
    val settingsDefaults: String,
    val settingsDefaultModel: String,
    val settingsDefaultSize: String,
    val settingsSave: String,
    val settingsAbout: String,
    val settingsAboutDesc: String,
    val settingsModels: String,
    val settingsLanguage: String,

    // Common
    val modelLabel: String,
    val sizeLabel: String,

    // Error messages
    val errApiKey: String,
    val errInvalidKey: String,
    val errRateLimit: String,
    val errContentSafety: String,
    val errNetwork: String,
    val errServer: String,
    val errUnknown: String,
    val errEnterPrompt: String,
    val errSelectImage: String,
    val errEnterEditPrompt: String,
    val errSetApiKey: String,
    val errEmptyResponse: String,
    val errUnknownApi: String,
    val errNoImageGenerated: String,
    val errNoImageUrl: String,
    val errSaveFailed: String,
    val errEditSaveFailed: String,
    val errCannotOpen: String,
    val errDecodeFailed: String
) {
    companion object {
        val ZH = AppStrings(
            navGenerate = "生成",
            navEdit = "编辑",
            navGallery = "相册",
            navSettings = "设置",
            txt2imgTitle = "文生图",
            txt2imgPromptLabel = "提示词",
            txt2imgPromptPlaceholder = "描述你想生成的图片...",
            txt2imgNegLabel = "反向提示词（可选）",
            txt2imgNegPlaceholder = "不想出现的内容...",
            txt2imgModel = "模型",
            txt2imgSize = "尺寸",
            txt2imgButton = "生成图片",
            editTitle = "图像编辑",
            editTapToSelect = "点击选择图片",
            editFromLibrary = "从相册中选择",
            editSourceDesc = "原图",
            editChange = "更换",
            editPromptLabel = "编辑提示词",
            editPromptPlaceholder = "描述你想如何编辑图片...",
            editModel = "模型",
            editButton = "编辑图片",
            galleryTitle = "相册",
            galleryEmpty = "暂无图片",
            galleryEmptyHint = "生成你的第一张图片吧！",
            galleryImageNotFound = "图片未找到",
            gallerySave = "保存到相册",
            galleryShare = "分享",
            galleryDelete = "删除",
            galleryCopyPrompt = "复制提示词",
            galleryPromptCopied = "提示词已复制",
            galleryShareTitle = "分享图片",
            viewerTitle = "图片详情",
            viewerBack = "返回",
            viewerSave = "保存",
            viewerShare = "分享",
            viewerDelete = "删除",
            viewerShareTitle = "分享图片",
            viewerDesc = "原图查看",
            viewerNotFound = "图片未找到",
            resultDesc = "生成的图片",
            resultTxt2img = "文生图",
            resultEdit = "图像编辑",
            resultSave = "保存",
            resultShare = "分享",
            resultShareTitle = "分享图片",
            resultSavedBy = "由 Qwen Image 生成",
            loadingMsg = "正在生成图片...",
            loadingHint = "预计需要 10-30 秒",
            settingsTitle = "设置",
            settingsSaved = "设置已保存",
            settingsApiConfig = "API 配置",
            settingsApiKeyLabel = "DashScope API Key",
            settingsApiPlaceholder = "sk-...",
            settingsHide = "隐藏",
            settingsShow = "显示",
            settingsApiKeyHint = "请输入阿里云百炼平台的 DashScope API Key。",
            settingsDefaults = "默认设置",
            settingsDefaultModel = "默认模型",
            settingsDefaultSize = "默认尺寸",
            settingsSave = "保存设置",
            settingsAbout = "关于",
            settingsAboutDesc = "基于阿里云百炼 DashScope API",
            settingsModels = "模型：qwen-image-2.0-pro / qwen-image-2.0",
            settingsLanguage = "语言",
            modelLabel = "模型",
            sizeLabel = "尺寸",
            errApiKey = "请先在设置中配置 API Key",
            errInvalidKey = "API Key 无效，请在设置中检查。",
            errRateLimit = "请求频率过高，请稍后再试。",
            errContentSafety = "内容安全审核未通过，请更换提示词重试。",
            errNetwork = "网络错误，请检查网络连接。",
            errServer = "服务器错误，请稍后重试。",
            errUnknown = "未知错误",
            errEnterPrompt = "请输入提示词",
            errSelectImage = "请选择一张图片",
            errEnterEditPrompt = "请输入编辑提示词",
            errSetApiKey = "请先在设置中配置 API Key",
            errEmptyResponse = "响应内容为空",
            errUnknownApi = "未知 API 错误",
            errNoImageGenerated = "未生成图片，提示词可能被内容安全过滤器拦截。",
            errNoImageUrl = "响应中未包含图片",
            errSaveFailed = "保存图片失败：",
            errEditSaveFailed = "保存编辑后的图片失败：",
            errCannotOpen = "无法打开图片",
            errDecodeFailed = "解码图片失败"
        )

        val EN = AppStrings(
            navGenerate = "Generate",
            navEdit = "Edit",
            navGallery = "Gallery",
            navSettings = "Settings",
            txt2imgTitle = "Text to Image",
            txt2imgPromptLabel = "Prompt",
            txt2imgPromptPlaceholder = "Describe the image you want to generate...",
            txt2imgNegLabel = "Negative Prompt (optional)",
            txt2imgNegPlaceholder = "What to avoid...",
            txt2imgModel = "Model",
            txt2imgSize = "Size",
            txt2imgButton = "Generate Image",
            editTitle = "Image Edit",
            editTapToSelect = "Tap to select an image",
            editFromLibrary = "Choose from your photo library",
            editSourceDesc = "Source image",
            editChange = "Change",
            editPromptLabel = "Editing Prompt",
            editPromptPlaceholder = "Describe how to edit the image...",
            editModel = "Model",
            editButton = "Edit Image",
            galleryTitle = "Gallery",
            galleryEmpty = "No images yet",
            galleryEmptyHint = "Generate your first image!",
            galleryImageNotFound = "Image not found",
            gallerySave = "Save to Gallery",
            galleryShare = "Share",
            galleryDelete = "Delete",
            galleryCopyPrompt = "Copy Prompt",
            galleryPromptCopied = "Prompt copied",
            galleryShareTitle = "Share Image",
            viewerTitle = "Image",
            viewerBack = "Back",
            viewerSave = "Save",
            viewerShare = "Share",
            viewerDelete = "Delete",
            viewerShareTitle = "Share Image",
            viewerDesc = "Full size image",
            viewerNotFound = "Image not found",
            resultDesc = "Generated image",
            resultTxt2img = "Text to Image",
            resultEdit = "Image Edit",
            resultSave = "Save",
            resultShare = "Share",
            resultShareTitle = "Share Image",
            resultSavedBy = "Generated by Qwen Image",
            loadingMsg = "Generating image...",
            loadingHint = "This may take 10-30 seconds",
            settingsTitle = "Settings",
            settingsSaved = "Settings saved",
            settingsApiConfig = "API Configuration",
            settingsApiKeyLabel = "DashScope API Key",
            settingsApiPlaceholder = "sk-...",
            settingsHide = "Hide",
            settingsShow = "Show",
            settingsApiKeyHint = "Enter your DashScope API key from Alibaba Cloud console.",
            settingsDefaults = "Defaults",
            settingsDefaultModel = "Default Model",
            settingsDefaultSize = "Default Size",
            settingsSave = "Save Settings",
            settingsAbout = "About",
            settingsAboutDesc = "Powered by Alibaba Cloud DashScope API",
            settingsModels = "Model: qwen-image-2.0-pro / qwen-image-2.0",
            settingsLanguage = "Language",
            modelLabel = "Model",
            sizeLabel = "Size",
            errApiKey = "Please set your API key in Settings",
            errInvalidKey = "Invalid API key. Please check Settings.",
            errRateLimit = "Rate limited. Please wait and try again.",
            errContentSafety = "Content safety check failed. Please try a different prompt.",
            errNetwork = "Network error. Please check your internet connection.",
            errServer = "Server error. Please try again later.",
            errUnknown = "Unknown error",
            errEnterPrompt = "Please enter a prompt",
            errSelectImage = "Please select an image",
            errEnterEditPrompt = "Please enter an editing prompt",
            errSetApiKey = "Please set your API key in Settings",
            errEmptyResponse = "Empty response body",
            errUnknownApi = "Unknown API error",
            errNoImageGenerated = "No images generated. The prompt may have been blocked by content safety filters.",
            errNoImageUrl = "No image URL in response",
            errSaveFailed = "Failed to save generated image: ",
            errEditSaveFailed = "Failed to save edited image: ",
            errCannotOpen = "Cannot open image",
            errDecodeFailed = "Failed to decode image"
        )
    }
}
